# ==================== Application ====================
spring.application.name=NMS
server.port=${PORT:8080}


# ==================== MongoDB Atlas ====================
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true



# ==================== JWT ====================
jwt.secretKey=${JWT_SECRET}


# ==================== OAuth2 Configuration ====================

# ==================== Google ====================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}


# ==================== GitHub ====================
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.redirect-uri=https://notes-management-system-1-9g7x.onrender.com/login/oauth2/code/google

frontend.redirect.url=https://nms-frontend-kohl.vercel.app
server.servlet.session.cookie.same-site=Lax
server.servlet.session.cookie.secure=true
